# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e66deb596211e722a2fd7eadd56756f31e334c12326b95c183974c2404766e2db05cd3cc4d3781a5345417e0988a21b7edc518e1630eae3ff3d934a72f1fa1f

test:
  secret_key_base: a2d4ce2e1e6a26ae975ac01f5d609636c4f93119d06778f72ced25eb5c5ae153567563ba1ff7bbf35fd6613552099b6c0c37e7a19ae34a6472f2ce18b0dba604

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
